version: '2'
services:
  zookeeper1:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  zookeeper2:
    image: wurstmeister/zookeeper
    ports:
      - "2182:2181"
  zookeeper3:
    image: wurstmeister/zookeeper
    ports:
      - "2183:2181"
  kafka1:
    image: wurstmeister/kafka
    ports:
      - "29092:29092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_NUM_PARTITIONS: 8
      # BOOTSTRAP_SERVERS: kafka:29092, kafka:39092, kafka:49092
      # KAFKA_CREATE_TOPICS: "leele-topic:8:3"
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper1:2181, zookeeper2:2182, zookeeper3:2183
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
      KAFKA_LISTENERS : PLAINTEXT://kafka1:9092, PLAINTEXT_HOST://kafka1:29092
      KAFKA_ADVERTISED_LISTENERS : PLAINTEXT://kafka1:9092, PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP : PLAINTEXT:PLAINTEXT, PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME : PLAINTEXT
      KAFKA_HEAP_OPTS: "-Xmx512M -Xms512M"
      KAFKA_DELETE_TOPIC_ENABLE: "true"
    depends_on:
      - "zookeeper1"
      - "zookeeper2"
      - "zookeeper3"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  kafka2:
    image: wurstmeister/kafka
    ports:
      - "39092:39092"
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_NUM_PARTITIONS: 8
      # BOOTSTRAP_SERVERS: kafka:29092, kafka:39092, kafka:49092
      # KAFKA_CREATE_TOPICS: "leele-topic:8:3"
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper1:2181, zookeeper2:2182, zookeeper3:2183
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
      KAFKA_LISTENERS : PLAINTEXT://kafka2:9092, PLAINTEXT_HOST://kafka2:39092
      KAFKA_ADVERTISED_LISTENERS : PLAINTEXT://kafka2:9092, PLAINTEXT_HOST://localhost:39092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP : PLAINTEXT:PLAINTEXT, PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME : PLAINTEXT
      KAFKA_HEAP_OPTS: "-Xmx512M -Xms512M"
      KAFKA_DELETE_TOPIC_ENABLE: "true"
    depends_on:
      - "zookeeper1"
      - "zookeeper2"
      - "zookeeper3"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  kafka3:
    image: wurstmeister/kafka
    ports:
      - "49092:49092"
    environment:
      KAFKA_BROKER_ID: 3
      KAFKA_NUM_PARTITIONS: 8
      # BOOTSTRAP_SERVERS: kafka:29092, kafka:39092, kafka:49092
      # KAFKA_CREATE_TOPICS: "leele-topic:8:3"
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper1:2181, zookeeper2:2182, zookeeper3:2183
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
      KAFKA_LISTENERS : PLAINTEXT://kafka3:9092, PLAINTEXT_HOST://kafka3:49092
      KAFKA_ADVERTISED_LISTENERS : PLAINTEXT://kafka3:9092, PLAINTEXT_HOST://localhost:49092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP : PLAINTEXT:PLAINTEXT, PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME : PLAINTEXT
      KAFKA_HEAP_OPTS: "-Xmx512M -Xms512M"
      KAFKA_DELETE_TOPIC_ENABLE: "true"
    depends_on:
      - "zookeeper1"
      - "zookeeper2"
      - "zookeeper3"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  kafdrop:
    image: obsidiandynamics/kafdrop
    restart: "no"
    ports:
      - "9000:9000"
    environment:
      HOST: 127.0.0.1
      KAFKA_BROKERCONNECT: "kafka1:9092"
      JVM_OPTS: "-Xms32M -Xmx64M"
    depends_on:
      - kafka1
      - kafka2
      - kafka3